-- CREATION DES ROLES
CREATE ROLE R_CLIENT_ADMIN30;
GRANT SELECT ON Contact_ADMIN30 TO R_CLIENT_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_CLIENT_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_CLIENT_ADMIN30;

CREATE ROLE R_INFORMATICIEN_ADMIN30;
-- GRANT R_CLIENT_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT SELECT ON Contact_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT UPDATE ON Contact_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT INSERT, DELETE ON Calendrier_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT INSERT ON Evenement_ADMIN30 TO R_INFORMATICIEN_ADMIN30;

CREATE ROLE R_COMMERCIAL_ADMIN30;
-- GRANT R_INFORMATICIEN_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT UPDATE ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT, DELETE ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Evenement_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;

CREATE ROLE R_ADMIN_ADMIN30;
GRANT ALL ON Contact_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT ALL ON Calendrier_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT ALL ON Evenement_ADMIN30 TO R_ADMIN_ADMIN30;

-- ATTRIBUTION DES ROLES
GRANT R_ADMIN_ADMIN30 TO USER2;
GRANT R_COMMERCIAL_ADMIN30 TO USER5, USER6;
GRANT R_INFORMATICIEN_ADMIN30 TO USER1;
GRANT R_CLIENT_ADMIN30 TO USER3, USER4, USER7;
