DROP TABLE Calendrier_ADMIN30;
DROP TABLE Evenement_ADMIN30;
DROP TABLE Contact_ADMIN30;


REVOKE R_ADMIN_ADMIN30 FROM USER2;
REVOKE R_COMMERCIAL_ADMIN30 FROM USER5, USER6;
REVOKE R_INFORMATICIEN_ADMIN30 FROM USER1;
REVOKE R_CLIENT_ADMIN30 FROM USER3, USER4, USER7;


DROP ROLE R_CLIENT_ADMIN30;
DROP ROLE R_INFORMATICIEN_ADMIN30;
DROP ROLE R_COMMERCIAL_ADMIN30;
DROP ROLE R_ADMIN_ADMIN30;

DROP CONTEXT CAL_CTX_ADMIN30;
DROP PACKAGE set_cal_ctx_pkg_admin30;

DBMS_RLS.DROP_POLICY(
    object_schema => 'dba',
    object_name => 'Contact_ADMIN30',
    policy_name => 'ctc_policy_admin30'
)

DROP FUNCTION auth_ctc_admin30;

COMMIT;