-- CREATION DES ROLES
CREATE ROLE R_CLIENT_ADMIN30;
GRANT SELECT ON Contact_ADMIN30 TO R_CLIENT_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_CLIENT_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_CLIENT_ADMIN30;

CREATE ROLE R_INFORMATICIEN_ADMIN30;
-- GRANT R_CLIENT_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT SELECT ON Contact_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT UPDATE ON Contact_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT INSERT ON Calendrier_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT DELETE ON Calendrier_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_INFORMATICIEN_ADMIN30;
GRANT INSERT ON Evenement_ADMIN30 TO R_INFORMATICIEN_ADMIN30;

CREATE ROLE R_COMMERCIAL_ADMIN30;
-- GRANT R_INFORMATICIEN_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT UPDATE ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT DELETE ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Evenement_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON VCalendrier_Evenement_Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;

CREATE ROLE R_ADMIN_ADMIN30;
GRANT ALL ON Contact_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT ALL ON Calendrier_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT ALL ON Evenement_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT SELECT ON VCalendrier_Evenement_Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;

-- ATTRIBUTION DES ROLES
GRANT R_CLIENT_ADMIN30 TO USER1, USER2, USER3;
GRANT R_COMMERCIAL_ADMIN30 TO USER4, USER5;
GRANT R_INFORMATICIEN_ADMIN30 TO USER6;
GRANT R_ADMIN_ADMIN30 TO USER7;

COMMIT;