/* POUR TRAVAILLER EN LOCAL */

CREATE USER ADMIN30 IDENTIFIED BY admin;
CREATE USER USER1 IDENTIFIED BY user;
CREATE USER USER2 IDENTIFIED BY user;
CREATE USER USER3 IDENTIFIED BY user;
CREATE USER USER4 IDENTIFIED BY user;
CREATE USER USER5 IDENTIFIED BY user;
CREATE USER USER6 IDENTIFIED BY user;
CREATE USER USER7 IDENTIFIED BY user;


GRANT CREATE SESSION TO ADMIN30;
GRANT CREATE TABLE TO ADMIN30;
GRANT CREATE VIEW TO ADMIN30;
GRANT CREATE SYNONYM TO ADMIN30;
GRANT CREATE PUBLIC SYNONYM TO ADMIN30;
GRANT CREATE ROLE TO ADMIN30;
GRANT CREATE PROCEDURE TO ADMIN30;
GRANT CREATE ANY CONTEXT TO ADMIN30;
GRANT CREATE ANY INDEX TO ADMIN30;
GRANT CREATE TRIGGER TO ADMIN30;
GRANT CREATE MATERIALIZED VIEW TO ADMIN30;
GRANT CREATE SEQUENCE TO ADMIN30;
GRANT CREATE TYPE TO ADMIN30;
GRANT EXECUTE ON DBMS_RLS TO role_vpd TO ADMIN30;


GRANT CREATE SESSION TO USER1;
GRANT CREATE SESSION TO USER2;
GRANT CREATE SESSION TO USER3;
GRANT CREATE SESSION TO USER4;
GRANT CREATE SESSION TO USER5;
GRANT CREATE SESSION TO USER6;
GRANT CREATE SESSION TO USER7;