/* GRANT ALL ON Contact_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT ALL ON Calendrier_ADMIN30 TO R_ADMIN_ADMIN30;
GRANT ALL ON Evenement_ADMIN30 TO R_ADMIN_ADMIN30; */

prompt "DOIT FONCTIONNER"

prompt "SELECT SUR TOUTES LES TABLES"
SELECT * FROM admin30.Contact_ADMIN30;
SELECT * FROM admin30.Evenement_ADMIN30;
SELECT * FROM admin30.Calendrier_ADMIN30;


prompt "DOIT NE PAS FONCTIONNER"