/* GRANT SELECT ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT SELECT ON Evenement_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT UPDATE ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT, DELETE ON Calendrier_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Evenement_ADMIN30 TO R_COMMERCIAL_ADMIN30;
GRANT INSERT ON Contact_ADMIN30 TO R_COMMERCIAL_ADMIN30; */

prompt "DOIT FONCTIONNER"

prompt "SELECT SUR TOUTES LES TABLES"
SELECT * FROM admin30.Contact_ADMIN30;
SELECT * FROM admin30.Evenement_ADMIN30;
SELECT * FROM admin30.Calendrier_ADMIN30;

SELECT * FROM admin30.Contact_ADMIN30 WHERE id='USER8' AND id_evenement=1;
INSERT INTO Contact_ADMIN30 (id, nom, prenom, telephone, courriel, categorie)
VALUES ('USER8', 'Testeur', 'Jean-Michel', 0777777777, 'mail8@gmail.com','Client');
SELECT * FROM admin30.Contact_ADMIN30 WHERE id='USER8';

prompt "DOIT NE PAS FONCTIONNER"